### PR TITLE
quick fixes for various issues

### PR DESCRIPTION
**Pull request by cwensel**
- added setting to flag fatjar
- increased exec timeout, large fatjars take a long time
- fixed path evaluations
- improved filtering of jdeps

don’t expect this PR to be blindly merged, but wanted to illustrate some of the issues I was having.

### CODE REVIEW

**Comment by cwensel** [comment]
added a new property referencing an alternative module home path so that one can build linux images on an osx machine.

**Comment by cwensel** [comment]
also a property to skip jdeps by simply finding all the java modules and adding them to jlink.

**Comment by alkimiapps** [comment]
Hi @cwensel . Thanks for these updates. I think they look pretty good. I have one question and one request. 

My question is about the allJavaModules option. Could you help me understand what that is giving us - I mean is there a difference between a JRE with all java modules and just an out-of-the-box JRE downloaded from Oracle or somewhere that has everything?

My request: please could you update the readme with your new options and a bit about what they do?

**Comment by cwensel** [comment]
Sure, happy to update the README.

the `allJavaModules` might be redundant, but the original intent was to speed up building of a java image if the fat jar was large (my current one is over 100mb, which I'm also trying to reduce, but if it was that easy, I would also be modularizing the app as well, which I've already abandoned). this forces jdeps to run for +10 minutes. in my case, the java image is intended to be included in a docker image. so this allows me to iteratively test the full tool chain faster.

for production builds, I would not set allJavaModules so the final java image is much smaller etc.

**Comment by cwensel** [comment]
README updated

**Comment by alkimiapps** [comment]
Make sense re: `allJavaModules` - +10 minutes added to the build time sounds painful. I read an article recently about some guys who made a maven plugin to do away with fatjars - been thinking a gradle plugin that does something similar might be useful. https://product.hubspot.com/blog/the-fault-in-our-jars-why-we-stopped-building-fat-jars.

Readme updates look good - could you fix the merge conflicts and I'll merge. Thanks.

I'll publish a v0.3 with your updates to gradle.org once that's done.

**Comment by cwensel** [comment]
OK, squashed all the commits, and rebased on your master.

**Pull request merged**
